algolia          :
  appId          : PDZK7H6PD0
  apiKey         : 911167d1e62d76e16e9cd746c0b1a684
  indexName      : dev_windsurf

meta             :
  appMountId     : "app"
  title          : "windtoday.co, windsurfing marketplace"
  baseHref       : "https://windtoday.co"
  description    : "windtoday is windsurfing marketplace to discover, compare & choose daily equipment offers. Pay and receive it at home, independently where you are."
  logoUrl"       : "https://blog.windtoday.co/logo.png"
  twitterAccount : "@windtodayco"
  googleAnalytics: "UA-85604345-1"
